# AEC config parameters for PBFDAF , DTD and NLP subsystems
SAMPLE_RATE = 16000
BLOCK_SIZE = 256
FFT_SIZE = 512
NUM_PARTITIONS = 16
STEP_SIZE = 0.15
EPSILON = 1e-10
DTD_COHERENCE_THRESHOLD=0.3
DTD_SMOOTHING_FACTOR= 0.9
NLP_AGGRESSIVENESS = 1.0
NLP_MIN_GAIN_DB = -25.0
NLP_MIN_GAIN_LINEAR = 10** (NLP_MIN_GAIN_DB / 20)

